spring:
  application:
    name: bank
  datasource:
    url: jdbc:mysql://localhost:3306/bank?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #15m
    refreshTokenExpiration: 604800 #7d